# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\2.Sınıf\1.Dönem\PYTHON\Proje\addProd.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(742, 472)
        self.txt_ad = QtWidgets.QTextEdit(dialog)
        self.txt_ad.setGeometry(QtCore.QRect(100, 50, 211, 31))
        self.txt_ad.setObjectName("txt_ad")
        self.txt_url = QtWidgets.QTextEdit(dialog)
        self.txt_url.setGeometry(QtCore.QRect(100, 90, 211, 31))
        self.txt_url.setObjectName("txt_url")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 81, 31))
        self.label_2.setObjectName("label_2")
        self.btn_ekle = QtWidgets.QPushButton(dialog)
        self.btn_ekle.setGeometry(QtCore.QRect(320, 90, 75, 31))
        self.btn_ekle.setObjectName("btn_ekle")
        self.btn_kaydet = QtWidgets.QPushButton(dialog)
        self.btn_kaydet.setGeometry(QtCore.QRect(100, 340, 111, 31))
        self.btn_kaydet.setObjectName("btn_kaydet")
        self.btn_cwtest = QtWidgets.QPushButton(dialog)
        self.btn_cwtest.setGeometry(QtCore.QRect(574, 340, 91, 23))
        self.btn_cwtest.setObjectName("btn_cwtest")
        self.crawl_result = QtWidgets.QLabel(dialog)
        self.crawl_result.setGeometry(QtCore.QRect(450, 340, 101, 21))
        self.crawl_result.setText("")
        self.crawl_result.setObjectName("crawl_result")
        self.lbx_url = QtWidgets.QListWidget(dialog)
        self.lbx_url.setGeometry(QtCore.QRect(410, 40, 301, 271))
        self.lbx_url.setObjectName("lbx_url")
        self.label.setBuddy(self.txt_ad)
        self.label_2.setBuddy(self.txt_url)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        dialog.setTabOrder(self.txt_ad, self.txt_url)
        dialog.setTabOrder(self.txt_url, self.btn_ekle)
        dialog.setTabOrder(self.btn_ekle, self.btn_kaydet)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Ürün Ekle"))
        self.label.setText(_translate("dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Ürün Adı</span></p></body></html>"))
        self.label_2.setText(_translate("dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Ürün URL</span></p></body></html>"))
        self.btn_ekle.setText(_translate("dialog", "Ekle"))
        self.btn_kaydet.setText(_translate("dialog", "Kaydet"))
        self.btn_cwtest.setText(_translate("dialog", "Crawl Test"))
