# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\OSMAN\Desktop\OsmanUni\python\ProjeOdevi\Proje\addProd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(673, 472)
        self.textEdit = QtWidgets.QTextEdit(dialog)
        self.textEdit.setGeometry(QtCore.QRect(100, 50, 211, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(100, 90, 211, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(30, 50, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 61, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(320, 90, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.tableView = QtWidgets.QTableView(dialog)
        self.tableView.setGeometry(QtCore.QRect(410, 10, 256, 321))
        self.tableView.setObjectName("tableView")
        self.pushButton_2 = QtWidgets.QPushButton(dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 340, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(574, 340, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.crawl_result = QtWidgets.QLabel(dialog)
        self.crawl_result.setGeometry(QtCore.QRect(450, 340, 101, 21))
        self.crawl_result.setText("")
        self.crawl_result.setObjectName("crawl_result")
        self.label.setBuddy(self.textEdit)
        self.label_2.setBuddy(self.textEdit_2)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        dialog.setTabOrder(self.textEdit, self.textEdit_2)
        dialog.setTabOrder(self.textEdit_2, self.pushButton)
        dialog.setTabOrder(self.pushButton, self.pushButton_2)
        dialog.setTabOrder(self.pushButton_2, self.tableView)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Ürün Ekle"))
        self.label.setText(_translate("dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Ürün Adı</span></p></body></html>"))
        self.label_2.setText(_translate("dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Ürün URL</span></p></body></html>"))
        self.pushButton.setText(_translate("dialog", "Ekle"))
        self.pushButton_2.setText(_translate("dialog", "Kaydet"))
        self.pushButton_3.setText(_translate("dialog", "Crawl Test"))
