# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\OSMAN\Desktop\OsmanUni\python\ProjeOdevi\Proje\listele.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 715)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbwg_listele = QtWidgets.QTableView(self.centralwidget)
        self.tbwg_listele.setGeometry(QtCore.QRect(0, 50, 951, 571))
        self.tbwg_listele.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbwg_listele.setAlternatingRowColors(True)
        self.tbwg_listele.setObjectName("tbwg_listele")
        self.btn_listele = QtWidgets.QPushButton(self.centralwidget)
        self.btn_listele.setGeometry(QtCore.QRect(880, 620, 75, 23))
        self.btn_listele.setObjectName("btn_listele")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 81, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 21))
        self.menubar.setObjectName("menubar")
        self.menuCrawler = QtWidgets.QMenu(self.menubar)
        self.menuCrawler.setObjectName("menuCrawler")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_r_n_Ekle = QtWidgets.QAction(MainWindow)
        self.action_r_n_Ekle.setObjectName("action_r_n_Ekle")
        self.menuCrawler.addAction(self.action_r_n_Ekle)
        self.menubar.addAction(self.menuCrawler.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ana Sayfa"))
        self.btn_listele.setText(_translate("MainWindow", "Listele"))
        self.label.setText(_translate("MainWindow", " Aktif Ürünler"))
        self.menuCrawler.setTitle(_translate("MainWindow", "Crawler"))
        self.action_r_n_Ekle.setText(_translate("MainWindow", "Ürün Ekle"))
