# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\OSMAN\Desktop\OsmanUni\python\ProjeOdevi\Proje\prodDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProdDialog(object):
    def setupUi(self, ProdDialog):
        ProdDialog.setObjectName("ProdDialog")
        ProdDialog.resize(770, 677)
        self.label = QtWidgets.QLabel(ProdDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 41))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(ProdDialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 180, 771, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(ProdDialog)
        self.pushButton.setGeometry(QtCore.QRect(180, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(ProdDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 30, 131, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(ProdDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ProdDialog)
        self.label_3.setGeometry(QtCore.QRect(120, 110, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ProdDialog)
        self.label_4.setGeometry(QtCore.QRect(220, 110, 81, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(ProdDialog)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 150, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(ProdDialog)
        self.label_5.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(ProdDialog)
        self.label_6.setGeometry(QtCore.QRect(220, 130, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(ProdDialog)
        self.label_7.setGeometry(QtCore.QRect(120, 130, 81, 16))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(ProdDialog)
        QtCore.QMetaObject.connectSlotsByName(ProdDialog)

    def retranslateUi(self, ProdDialog):
        _translate = QtCore.QCoreApplication.translate
        ProdDialog.setWindowTitle(_translate("ProdDialog", "Dialog"))
        self.label.setText(_translate("ProdDialog", "<html><head/><body><p><span style=\" font-size:18pt;\">Ürün Adı</span></p></body></html>"))
        self.pushButton.setText(_translate("ProdDialog", "Crawl"))
        self.pushButton_2.setText(_translate("ProdDialog", "Crawl Saatlerini Düzenle"))
        self.label_2.setText(_translate("ProdDialog", "En Düşük Fiyat"))
        self.label_3.setText(_translate("ProdDialog", "Ortalama Fiyat"))
        self.label_4.setText(_translate("ProdDialog", "En Yüksek Fiyat"))
        self.pushButton_3.setText(_translate("ProdDialog", "Grafik Göster"))
        self.label_5.setText(_translate("ProdDialog", "<html><head/><body><p align=\"center\">15</p></body></html>"))
        self.label_6.setText(_translate("ProdDialog", "<html><head/><body><p align=\"center\">15</p></body></html>"))
        self.label_7.setText(_translate("ProdDialog", "<html><head/><body><p align=\"center\">15</p></body></html>"))
