# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\OSMAN\Desktop\OsmanUni\python\ProjeOdevi\Proje\prodDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProdDialog(object):
    def setupUi(self, ProdDialog):
        ProdDialog.setObjectName("ProdDialog")
        ProdDialog.resize(1328, 1055)
        self.urunAdi = QtWidgets.QLabel(ProdDialog)
        self.urunAdi.setGeometry(QtCore.QRect(30, 20, 1281, 41))
        self.urunAdi.setObjectName("urunAdi")
        self.tableView = QtWidgets.QTableView(ProdDialog)
        self.tableView.setGeometry(QtCore.QRect(0, 180, 1331, 871))
        self.tableView.setObjectName("tableView")
        self.crawl = QtWidgets.QPushButton(ProdDialog)
        self.crawl.setGeometry(QtCore.QRect(1140, 140, 75, 23))
        self.crawl.setObjectName("crawl")
        self.label_2 = QtWidgets.QLabel(ProdDialog)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ProdDialog)
        self.label_3.setGeometry(QtCore.QRect(120, 110, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ProdDialog)
        self.label_4.setGeometry(QtCore.QRect(220, 110, 81, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(ProdDialog)
        self.pushButton_3.setGeometry(QtCore.QRect(1230, 140, 81, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.minFiyat = QtWidgets.QLabel(ProdDialog)
        self.minFiyat.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.minFiyat.setObjectName("minFiyat")
        self.maxFiyat = QtWidgets.QLabel(ProdDialog)
        self.maxFiyat.setGeometry(QtCore.QRect(220, 130, 81, 16))
        self.maxFiyat.setObjectName("maxFiyat")
        self.avgFiyat = QtWidgets.QLabel(ProdDialog)
        self.avgFiyat.setGeometry(QtCore.QRect(120, 130, 81, 16))
        self.avgFiyat.setObjectName("avgFiyat")
        self.crawlText = QtWidgets.QLabel(ProdDialog)
        self.crawlText.setGeometry(QtCore.QRect(180, 60, 47, 13))
        self.crawlText.setText("")
        self.crawlText.setObjectName("crawlText")

        self.retranslateUi(ProdDialog)
        QtCore.QMetaObject.connectSlotsByName(ProdDialog)

    def retranslateUi(self, ProdDialog):
        _translate = QtCore.QCoreApplication.translate
        ProdDialog.setWindowTitle(_translate("ProdDialog", "Ürün"))
        self.urunAdi.setText(_translate("ProdDialog", "<html><head/><body><p><span style=\" font-size:18pt;\">Ürün Adı</span></p></body></html>"))
        self.crawl.setText(_translate("ProdDialog", "Crawl"))
        self.label_2.setText(_translate("ProdDialog", "En Düşük Fiyat"))
        self.label_3.setText(_translate("ProdDialog", "Ortalama Fiyat"))
        self.label_4.setText(_translate("ProdDialog", "En Yüksek Fiyat"))
        self.pushButton_3.setText(_translate("ProdDialog", "Grafik Göster"))
        self.minFiyat.setText(_translate("ProdDialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.maxFiyat.setText(_translate("ProdDialog", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><br/></p></body></html>"))
        self.avgFiyat.setText(_translate("ProdDialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
